# Generated by Django 2.2.6 on 2019-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comunication_usernet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='zdj',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
