# Generated by Django 2.2.6 on 2019-11-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191111_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunication',
            name='temat',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
