# Generated by Django 2.2.6 on 2019-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191118_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunication',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='comunication',
            name='imie',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='comunication',
            name='nazwisko',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
