# Generated by Django 2.2.6 on 2019-11-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191125_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comunication',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='comunication',
            name='nazwisko',
        ),
    ]
